### ISSUE TITLE
Review Product Requirement README Link for fit

### ISSUE THREAD

**Issue by MichaelHirn** [kbariotis/templates#7]
I would like to use the Product Requirement Template, but find it hard to understand what the subsections should cover/should not cover - as there is no explanation.

[The link](https://www.atlassian.com/agile/product-management/requirements) in the README for the Requirement Template makes things even more confusing as there is no overlap between the headlines in the template and the headlines used in the link. Usually the links in the README explains the template but this one just makes it more confusing.

**Comment by kbariotis** [comment]
@MichaelHirn you are right, I have probably renamed these sections while transferring them to the template. It would be best to write exactly as in the example link to not confuse people. Thanks a ton for raising this.
